spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/search_structure?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root

logging:
  level:
    com.ppl.mybatisp.mapper: debug # 改成你的dao接口文件所在包路径可以打印出sql语句